### ISSUE TITLE
Lag Spike

### ISSUE THREAD

**Issue by SavvyWizardMan** [colleennicole223/odin-etch-a-sketch#1]
`color.addEventListener("input", () =>{ // using input as the event lags the color input. Use "change" instead.
    squares.forEach(square => {
        updateListener(square, color.value, draw, pen);
    });
})`

**Comment by colleennicole223** [comment]
Thank you for taking the time to review my code, I didn't realize how often the 'input' event fires 

Fixed with commit 31533c4bcb666d506c2f786e3d39991c49716cae
